config/routes.rb
Anysite::Application.routes.draw do

  namespace :admin do
      resources :templates
      resources :contents do
        resources :comments
      end
      resources :folders
      resources :resources
      match 'index' => 'admin#index'
      match 'contents/tree_node/:id' => 'contents#tree_node'
      match 'folders/tree_node/:id' => 'folders#tree_node'
      match 'resources/update_positions' => 'resources#update_positions'
      match 'contents/order' => 'contents#order'
      match 'contents/order_resources' => 'contents#order_resources'
      match 'folders/order_folders' => 'folders#order_folders'
      match 'folders/order_resources' => 'folders#order_resources'
      match 'contents/import/:id/:type/:object_id' => "contents#import"
  end
  
  
  namespace :site do
    match '*url' => 'contents#by_url'
  end
  
  match 'contact_us' => 'email#contact_us'
      

  devise_for :users

  root :to => "site/contents#index"

end

app/models/content.rb
class Content < ActiveRecord::Base
  include UrlHelper
  acts_as_tree
  acts_as_list :scope => "ancestry"
  has_many :content_resources
  has_many :resources, :through => :content_resources, :order => "content_resources.position ASC"
  has_one :creator, :foreign_key => "created_by"
  has_one :editor, :foreign_key => "edited_by" 
  has_many :comments, :as => :commentable
  default_scope :order => "position ASC"
  validates_presence_of :name, :message => "can't be blank"
  validates_uniqueness_of :slug, :scope => :ancestry
  validates_uniqueness_of :url, :scope => :ancestry
  
  searchable do
    text :html, :description, :stored => true
    string :name, :url, :ancestry
    integer :id
    integer :parent_id
  end
end

app/controllers/admin/contents_controller.rb
class Admin::ContentsController < ApplicationController
  before_filter :authenticate_user!
  
  def update_positions
  end
  
  def destroy
    child = Content.find(params[:id])
    @content = child.parent
    child.destroy
  end
  
  def edit
    @content = Content.find(params[:id])
    render :editor
  end
  
  def new
    @parent = Content.find(params[:parent_id])
    @content = Content.new
    render :editor
  end
  
  def create
    @parent = Content.find(params[:target_id])
    gen_slug params
    gen_url_on_create(params, @parent)
    @content = @parent.children.new(params[:content])
    @content.save
    render "editor"
  end
  
  def update
    @content = Content.find(params[:id])
    if(params[:content][:name])
      old_slug = @content.slug
      gen_slug params
      gen_url params
    end
    if @content.update_attributes(params[:content])
      UrlHelper.update_children_urls(@content) if old_slug != @content.slug
      puts "Gravado com sucesso"
    end
    render "update"
  end
  
  def tree_node
    @content = Content.find(params[:id])
  end
  
  def order
    params[:content_contents].each_with_index do |id, position|
      Content.update(id, :position => position+1)
    end
    render :nothing => true
  end
  
  def order_resources
    params[:content_resources].each_with_index do |resource_id, position|
      cr = ContentResource.find_by_content_id_and_resource_id(params[:content_id], resource_id)
      puts cr.position
      cr.content_id = params[:content_id]
      cr.resource_id = resource_id
      cr.position = position
      cr.save
      # ContentResource.update(id, :position => position+1)
    end
    render :nothing => true
  end
  
  def import
    Content.find(params[:id]).send(params[:type] + "s") << params[:type].capitalize.constantize.find(params[:object_id])
  end
  
  def search
    @search = Content.search() do
      keywords(params[:q])
    end
  end
  
  private
  
  def gen_slug(params)
    params[:content][:slug]=UrlHelper.slug(params[:content][:name])
  end
  
  def gen_url(params)
    params[:content][:url]=UrlHelper.url(@content, params[:content][:name]) if params[:id]
  end
  
  def gen_url_on_create(params, parent)
    params[:content][:url] = parent.url ? parent.url + "/" + params[:content][:slug] : "" + params[:content][:slug]
  end
    
end

app/controllers/site/contents_controller.rb
class Site::ContentsController < ApplicationController
  layout 'site'
  
  def show
    @content = Content.find(params[:id])
  end
  
  def by_url
    @content = Content.find_by_url(params[:url])
    render 'show'
  end
  
  def index
    @content = Content.first
    render 'show'
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
  
  def getHomepage(content)
    if(content.ancestry)
      homepage_id = @content.ancestry.gsub(/\/.*/,"")
      @homepage = Content.find(homepage_id)
    else
      @homepage = content
    end
  end
end

app/views/admin/contents/_edit.html.erb
<% form_tag admin_content_path(@content), :method => :put, :remote => true do %>
  <%= render :partial => inner_form %>
<% end %>

app/views/admin/contents/_editor.html.erb
<div id="editor_content_<%= @content.id %>" title="<%= @content.name %>">
	<%= link_to(image_tag("/images/admin/button_refresh.png"), edit_admin_content_path(@content), :remote => true, :id => "tatata", :class => "refresh") if !@content.id.nil? %>
	<ul class="tabs">
		<li id="main_tab" class="first"><a href="#main_tab_content">Geral</a></li>
		<li id="html_tab"><a href="#html_tab_content">Html</a></li>
    <li id="contents_tab"><a href="#contents_tab_content">Contents</a></li>
    <li id="resources_tab" class="last"><a href="#resources_tab_content"><span>Resources</span></a></li>
	</ul>
	<br clear="all"/>
	<div class="hide">
		<input type="button" id="temp" class="tab_cb_copy cb_copy" value="copy"/>
		<input type="text" value="content_<%= @content.id %>"/>
	</div>
	<div class="hide">
		<input type="button" value="Import"/>
		<input id="import_action" type="text" value="/admin/contents/import/<%=@content.id%>/"/>
	</div>
	<div id="tabscontent">
		<%if @content.id then%>
			<div id="main_tab_content" class="tab_content" style="">
			<%= render :partial => 'edit', :locals => { :inner_form => 'form_general' }  %>
	    </div>	
			<div id="html_tab_content">
				<%= render :partial => 'edit', :locals => { :inner_form => 'form_html' }  %>
			</div>
			<div id="contents_tab_content" class="tab_content" style="display:none;">
	        <%= render :partial => 'contents' %>
	    </div>
	    <div id="resources_tab_content" class="tab_content" style="display:none;">
	        <%= render :partial => 'resources' %>
	    </div>
		<% else %>
			<div id="main_tab_content" class="tab_content" style="">
				<%= render :partial => 'new'%>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/contents/_form_general.html.erb
<!--[form:page]-->
<p><label for="content_name">Name::<%=@content.slug%>::<%=@content.id%>::<%=@content.ancestry%>::<%=@content.url%></label>
<%= text_field 'content', 'name', :class => "std_input_text"  %></p>

<p><label for="content_menu">Menu</label>
<%= text_field 'content', 'menu'  %></p>

<p><label for="content_description">Description</label>
<%= text_field 'content', 'description'  %></p>

<p><label for="content_template">Template</label>
<%= text_field 'content', 'template'  %></p>

<p><label for="content_partial_template">Partial Template</label>
<%= text_field 'content', 'partial_template'  %></p>

<%= submit_tag "Salvar", :name => nil %>
<!--[eoform:page]-->

app/views/admin/contents/_form_html.html.erb
<!--[form:page]-->
<p><label for="content_name">Html</label> <input type="button" class="edit_html" value="edit"/></p>
<p class="html_output"><%= @content.html.html_safe if @content.html%></p>
<p><%= text_area 'content', 'html', :id => "editor_content_#{@content.id}_html_input", :class => 'text_editor', :style => 'display:none;'  %>
</p>

<%= submit_tag "Salvar", :name => nil %>
<!--[eoform:page]-->

app/views/admin/contents/_new.html.erb
<% form_tag( admin_contents_path,:remote => true, :id => 'content_form', :class => 'in_target' ) do %>
	<%= text_field_tag 'target_id', @parent.id%>
  <%= render :partial => 'form_general' %>
<% end %>

app/views/admin/contents/_resources.html.erb
<ul id="content_resources" class="sortable">
	<% if(@content.id) then @content.resources.each do |resource| %>    
  	<li id="content_resource_<%= resource.id %>">
			<div class="handle">
				<%= image_tag "admin/tree/open.png"%>&nbsp;
					<%= link_to resource.name, edit_admin_resource_path(resource), :remote => true %>
			</div>
			<%= link_to image_tag("admin/tree/trash.png"), admin_content_path(@content, resource), :confirm => 'Are you sure?', :method => 'remove_resource', :remote => true %>
			<br clear="all"/>
		</li>
	<% end end %>
</ul>
<%#= sortable_element('content_resources', :url => {:controller => 'contents', :action => "order_resources"}, :handle => "handle") %>
<%= sortable_element('content_resources', :url => { :controller => 'contents', :action => "order_resources", :content_id => @content.id}) %>

app/views/admin/contents/_tree_node.html.erb
<% if !@content.children.empty? %>
<ul id="content_<%= @content.id %>_ul">
<% for subcontent in @content.children%>
	<%= render :partial => 'tree_node_child', :locals => {:subcontent => subcontent}%>
<% end%>
</ul>
<% end %>

app/views/admin/contents/_tree_node_child.html.erb
<li id="content_<%= subcontent.id %>">
		<%= link_to image_tag("admin/tree/closed.png"), {:controller => "contents", :action => "tree_node", :id => subcontent.id}, :remote => true, :class => "tree_node_icon" %>
		<%= link_to "#{subcontent.name} (#{subcontent.children.size})" , edit_admin_content_path(subcontent), :remote => true, :class => "tree_node" %>
</li>

app/views/admin/contents/destroy.js.erb
$("contents_tab_content").update("<%= escape_javascript(render :partial => 'contents') %>");

app/views/admin/contents/edit.js.erb
$("main_tab_content").update("<%= escape_javascript(render :partial => 'edit') %>");

app/views/admin/contents/editor.js.erb
<% id = @content.id.nil? ? 0 : @content.id %>
var editor_content_<%= id %> = editor.windowFactory('content', <%= id %>, '<%= @content.name %>');
window_container = editor_content_<%= id %>.container
window_container.insert("<%= escape_javascript(render :partial => 'editor') %>");
window_container.down(".window_refresh").insert(window_container.down(".refresh"));
editor.createTabControl(window_container.down("ul.tabs"), {
	tabs_container: window_container
	});

app/views/admin/contents/show.js.erb
$("editor").update("<%= escape_javascript(render :partial => 'editor') %>");

app/views/admin/contents/tree_node.js.erb
$('content_<%=@content.id%>').insert("<%= escape_javascript(render :partial => "tree_node") %>")

app/views/admin/contents/update.js.erb
<%= render :template => '/admin/contents/editor' %>
<% if @content.parent%>
	tree.closeFolder('content_<%=@content.parent.id%>');
	var evt = document.createEvent("HTMLEvents")
	evt.initEvent('click', true, true );
	$('content_<%=@content.parent.id%>').down().dispatchEvent(evt);
<% end %>