config/routes.rb
Anysite::Application.routes.draw do

  namespace :admin do
      resources :templates
      resources :contents do
        resources :comments
      end
      resources :folders
      resources :resources
      match 'index' => 'admin#index'
      match 'contents/tree_node/:id' => 'contents#tree_node'
      match 'folders/tree_node/:id' => 'folders#tree_node'
      match 'resources/update_positions' => 'resources#update_positions'
      match 'contents/order' => 'contents#order'
      match 'contents/order_resources' => 'contents#order_resources'
      match 'folders/order_folders' => 'folders#order_folders'
      match 'folders/order_resources' => 'folders#order_resources'
      match 'contents/import/:id/:type/:object_id' => "contents#import"
  end
  
  
  namespace :site do
    match '*url' => 'contents#by_url'
  end
  
  match 'contact_us' => 'email#contact_us'
      

  devise_for :users

  root :to => "site/contents#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
end

app/models/content.rb
class Content < ActiveRecord::Base
  include UrlHelper
  acts_as_tree
  acts_as_list :scope => "ancestry"
  has_many :content_resources
  has_many :resources, :through => :content_resources, :order => "content_resources.position ASC"
  has_one :creator, :foreign_key => "created_by"
  has_one :editor, :foreign_key => "edited_by" 
  has_many :comments, :as => :commentable
  default_scope :order => "position ASC"
  validates_presence_of :name, :message => "can't be blank"
  validates_uniqueness_of :slug, :scope => :ancestry
  validates_uniqueness_of :url, :scope => :ancestry
  
  searchable do
    text :html, :description, :stored => true
    string :name, :url, :ancestry
    integer :id
    integer :parent_id
  end
end

app/models/content_resource.rb
class ContentResource < ActiveRecord::Base
  belongs_to :resource
  belongs_to :content
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  acts_as_tree
  acts_as_list :scope => "ancestry"
  has_many :resources
  has_one :creator, :foreign_key => "created_by"
  has_one :editor, :foreign_key => "edited_by"
  default_scope :order => "position ASC"
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :folder
  acts_as_list
  has_one :creator, :foreign_key => "created_by"
  has_one :editor, :foreign_key => "edited_by"
  default_scope :order => "position ASC"  
  has_attached_file :source, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :path => ":rails_root/public/system/:attachment/:id/:style/:filename"
end

app/models/template.rb
class Template < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_user!
  layout "admin"

  def index
    @content = Content.first
    @folder = Folder.first
  end
  
  def lorem
    render :layout => false
  end
end

app/controllers/admin/folders_controller.rb
class Admin::FoldersController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    @folder = Folder.find(params[:id])
  end
  
  def edit
    @folder = Folder.find(params[:id])
    render "editor"
  end
  
  def new
    @target = Folder.find(params[:target_id])
    @folder = Folder.new
    render "editor"
  end
  
  def update
    @folder = Folder.find(params[:id])
    @folder.update_attributes(params[:folder])
  end
  
  def create
    @parent = Folder.find(params[:target_id])
    @folder = @parent.children.new(params[:folder])
    @folder.save
    render "form"
  end
  
  def destroy
    child = Folder.find(params[:id])
    @folder = child.parent
    child.destroy
  end
  
  def tree_node
    @folder = Folder.find(params[:id])
  end
  
  def order_resources
    params[:folder_resources].each_with_index do |id, position|
      Resource.update(id, :position => position+1)
    end
    render :nothing => true
  end
  
  def order_folders
    params[:folder_folders].each_with_index do |id, position|
      Folder.update(id, :position => position+1)
    end
    render :nothing => true
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def contact_us
    begin
      ContactMailer.contact_us(params[:email]).deliver 
      @message = "Email enviado com sucesso"
      params.delete :email
    rescue
      @message = "Occorreu um erro ao enviar o email."
    end
    @content = Content.find(params[:content_id])
    render :action => "layouts/site"
  end
end

app/controllers/site/contents_controller.rb
class Site::ContentsController < ApplicationController
  layout 'site'
  
  def show
    @content = Content.find(params[:id])
  end
  
  def by_url
    @content = Content.find_by_url(params[:url])
    render 'show'
  end
  
  def index
    @content = Content.first
    render 'show'
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
  
  def getHomepage(content)
    if(content.ancestry)
      homepage_id = @content.ancestry.gsub(/\/.*/,"")
      @homepage = Content.find(homepage_id)
    else
      @homepage = content
    end
  end
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
  def render_template(name)
    render :partial => "/site/templates/default/#{name}"
  end
end

app/helpers/url_helper.rb
module UrlHelper
  
  ACCENTS_MAPPING = {
      'E' => [200,201,202,203],
      'e' => [232,233,234,235],
      'A' => [192,193,194,195,196,197],
      'a' => [224,225,226,227,228,229,230],
      'C' => [199],
      'c' => [231],
      'O' => [210,211,212,213,214,216],
      'o' => [242,243,244,245,246,248],
      'I' => [204,205,206,207],
      'i' => [236,237,238,239],
      'U' => [217,218,219,220],
      'u' => [249,250,251,252],
      'N' => [209],
      'n' => [241],
      'Y' => [221],
      'y' => [253,255],
      'AE' => [306],
      'ae' => [346],
      'OE' => [188],
      'oe' => [189]
    }

  STRIPPABLE = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 14, 15, 16, 17, 18, 19,
      20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33, 34, 35, 36, 37, 38, 39,
      40, 41, 42, 43, 44, 45, 46, 47, 58, 59, 60, 61, 62, 63, 64, 91, 92, 93, 94,
      96, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
      137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
      152, 153, 154, 155, 156, 157, 158, 159, 161, 162, 163, 164, 165, 166, 167,
      168, 169, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 182, 183, 184,
      185, 187, 188, 189, 190, 191, 215, 247, 8203, 8204, 8205, 8239, 65279]
  
  def self.slug(name)
    self.removeaccents (name.unpack("U*") - STRIPPABLE).pack("U*").gsub("-", " ").squeeze(" ").strip.downcase.gsub(/\s/u, '-')
  end
  
  def self.removeaccents(str)
    ACCENTS_MAPPING.each {|letter,accents|
      packed = accents.pack('U*')
      rxp = Regexp.new("[#{packed}]", nil, 'U')
      str.gsub!(rxp, letter)
    }

    str
  end
  
  def self.url(object, name)
    if object.parent_id
      ancestry_ary = object.ancestry.split('/').drop(1) 
      url = String.new
      ancestry_ary.each { |object_id|
        url << "/" if url.length > 0
        url << object.class.find(object_id.to_i).slug
      }
      url << "/" if url.length > 0
      url << (name.nil? ? object.slug : slug(name))
      url
    end
  end
  
  def self.update_children_urls(object)
    object.children.each { |child|
      child.url = UrlHelper.url(child, nil)
      self.update_children_urls(child) if child.save
    }
  end

end

app/views/admin/admin/index.html.erb
		<div id="anysite_top"></div>
		<div id="navigation_menu" class="treeview">
			<ul id="any_folders" class="treeview">
				<%= render :partial => '/admin/contents/tree_node_child', :locals => { :subcontent => @content}%>
			</ul>
			<ul id="any_files" class="treeview">
				<%= render :partial => '/admin/folders/tree_node_child', :locals => { :subfolder => @folder } %>
			</ul>
		</div>
		<div id="taskbar"></div>



			<div id="editor_area">
				<div id="editor">
				</div>
			</div>
			<div id="windows">
			</div>




			<div id="folder_menu" class="skin0" style="display:none">

			<div><%= link_to "Nova Pasta" , :update => "editor", :url => {:controller => "folder", :action => "editor"}, :complete => "setTargetId()" %></div>
			<div><%= link_to "Nova Página" , :update => "editor", :url => {:controller => "page", :action => "editor"}, :complete => "setTargetId()" %></div>
			<hr>
			<div class="menuitems" url="mailto:dynamicdrive@yahoo.com">Email Us</div>
			</div>

			<div id="resource_folder_menu" class="skin0" display:none>
			<div><%= link_to "Novo Resource Folder" , :update => "editor", :url => {:controller => "resource_folder", :action => "editor"}, :complete => "setTargetId()" %></div>
			<div><%= link_to "Novo Recurso" , :update => "editor", :url => {:controller => "resource", :action => "editor"}, :complete => "setTargetId()" %></div>
			<hr>

<iframe id='upload_frame' name="upload_frame" style="width:1px;height:1px;border:0px" src="about:blank"></iframe>

			<div class="menuitems" url="mailto:dynamicdrive@yahoo.com">Email Us</div>
			</div>
			<div id="clipboard" style="position:absolute;bottom:0px;right:0px;">
				<div>Clipboard</div>
				<div id="clipboard_list">
					123
				</div>
			</div>
			<input id="selected_object" type='text' value="" style="display:none">
			<input id="right_clicked_item" type='text' value="" style="display:none">


			<script type="text/javascript">
				var current_object = "";

				//ddtreemenu.createTree(treeid, enablepersist, opt_persist_in_days (default is 1))

				//ddtreemenu.createTree("any_folders", false)
				//set this variable to 1 if you wish the URLs of the highlighted menu to be displayed in the status bar
				var display_url=0

				var ie5=document.all&&document.getElementById
				var ns6=document.getElementById&&!document.all
				/*if (ie5||ns6)
				var folder_menu=document.getElementById("folder_menu")

				if (ie5||ns6){
				//menuobj.style.display=''
				//document.oncontextmenu=showmenuie5
				document.onclick=hideAllMenu
				}*/
				document.onclick=hideAllMenu;
				var menus = new Array(document.getElementById("folder_menu"), document.getElementById("resource_folder_menu"))

			</script>

app/views/admin/admin/lorem.html.erb
lorem opa!

app/views/admin/resources/_edit.html.erb
<%= form_tag admin_resource_path, :method => :put, :id => 'resource_form', :multipart => true, :target => 'upload_frame' do %>
  <%= render :partial => 'form' %>
<% end -%>

app/views/admin/resources/_editor.html.erb
<div class="tabs">
    <ul>
        <li id="main_tab" class="tabHeaderActive tab_header">Geral</li>
        <li id="resource_refresh""><%= link_to("refresh", edit_admin_resource_path(@resource), :remote => true) if !@resource.id.nil? %></li>
    </ul>
</div>
<div>
	<input type="button" id="temp" class="tab_cb_copy cb_copy" value="copy"/>
	<input type="text" value="resources/<%= @resource.id %>"/>
</div>
<div id="tabscontent">
    <div id="main_tab_content" class="tab_content" style="">
	<%if @resource.id then%>
		<%= render :partial => 'edit' %>
	<% else %>
		<%= render :partial => 'new'%>
	<% end %>
    </div>

</div>

app/views/admin/resources/_form.html.erb
<p><label for="resource_name">Name</label><br/>
<%= text_field 'resource', 'name'  %></p>

<p><label for="resource_description">Description</label><br/>
<%= text_field 'resource', 'description'  %></p>



<p><label for="resource_source">File</label><br/>
<% if !@resource.id.nil? and @resource.source_content_type and @resource.source_content_type.include? 'image' then %>
<%= @resource.source.url%><br/>
<img src="<%=@resource.source.url(:thumb)%>"/>
<% end -%>
<%= file_field 'resource', :source %>

<br/>
content type: <%= @resource.source_content_type %><br/>
file size: <%=@resource.source_file_size%><br/>

<%= submit_tag "Salvar", :name => nil %>
<!--[eoform:page]-->

app/views/admin/resources/_new.html.erb
<% form_tag( admin_resources_path, :remote => true, :id => 'resource_form') do %>
	<%= text_field_tag 'target_id', @folder.id%>
  <%= render :partial => 'form' %>
<% end %>

app/views/admin/resources/create.js.erb
$("resource_form").update("<%= escape_javascript(render :partial => 'form') %>");

app/views/admin/resources/destroy.js.erb
$("resources_tab_content").update("<%= escape_javascript(render :partial => 'admin/folders/resources') %>");

app/views/admin/resources/editor.js.erb
$("editor").update("<%= escape_javascript(render :partial => 'editor') %>");

app/views/admin/resources/form.js.erb
$("resource_form").update("<%= escape_javascript(render :partial => 'form') %>");

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
 <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
	<link rel="shortcut icon" href="/favicon.png" type="image/png" />
 <title>Anysite - Admin</title>
	<%= javascript_include_tag :defaults %>
	<%= stylesheet_link_tag "reset" %>
	<%= stylesheet_link_tag "generic" %>
	<%= stylesheet_link_tag "admin/anysite" %>
	<%= stylesheet_link_tag "admin/tabs" %>
	<%= stylesheet_link_tag "admin/window" %>
	<%= stylesheet_link_tag "admin/form" %>
	<%= stylesheet_link_tag "simpletree" %>
	<%= stylesheet_link_tag "context_menu" %>
	<%= javascript_include_tag "admin/Editor" %>
	<%= javascript_include_tag "admin/Clipboard" %>
	<%= javascript_include_tag "admin/Tree" %>
	<%= javascript_include_tag "admin/context_menu" %>
	<%= javascript_include_tag "admin/tiny_mce/tiny_mce.js" %>
	<%= javascript_include_tag "admin/livepipe/livepipe" %>
	<%= javascript_include_tag "admin/livepipe/window" %>
	<%= javascript_include_tag "admin/livepipe/resizable" %>
	<%= javascript_include_tag "admin/livepipe/tabs" %>
	<%= csrf_meta_tag %>
</head>
<body onload="init_admin();">
<%= yield  %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anysite</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/site.html.erb
<%= render_template @content.template.blank? ? 'content' : @content.template %>

app/views/site/templates/default/_contact_us.html.erb
Message: <%= @message %><br/>
<%= form_tag  '/contact_us' do%>
<p><label for="email_from">Email</label><%= text_field_tag 'email[from]', params[:email].nil? ? "": params[:email][:from] %></p>
<p><label for="email_subject">Subject</label><%= text_field_tag 'email[subject]', params[:email].nil? ? "": params[:email][:subject] %></p>
<p><label for="email_message">Message</label><%= text_area_tag 'email[message]', params[:email].nil? ? "": params[:email][:message] %></p>
<%= hidden_field_tag 'content_id', @content.id%>
<%= submit_tag "enviar", :name => nil %>
<% end -%>

app/views/site/templates/default/_content.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
	<title>:. Anyware Technologies .:</title>
	<link rel="shortcut icon" href="favicon.png" type="image/png" />
	<%= javascript_include_tag :defaults %>
	<%= stylesheet_link_tag "site/site.css" %>
	<%= stylesheet_link_tag "site/cssmenus" %>
	<%= javascript_include_tag "site/cssmenus" %>
	<!--[if gte IE 5.5]>
	<%= javascript_include_tag "site/cssmenus" %>
	<![endif]-->

	<meta name="author" content="Anyware Technologies"/>
  <meta name="DC.title" content="Anyware Technologies" /> 
  <meta name="DC.subject" content="projetos, lean, agile, kanban, ruby on rails" /> 
  <meta name="DC.description" content="Site oficial de Anyware Technologies" /> 
  <meta name="DC.format" content="text/html" /> 
  <meta name="DC.publisher" content="Anyware Technologies" /> 
  <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" /> 
</head> 
<body> 
  <div id="wrapper"> 
		<div id="main">
			<div id='header'>
				<%= render_template 'top' %>
			</div>
			<div id="navigation">
				<ul id="navmenu-h">
					<%= render_template 'menu'%>
				</ul>
			</div>
			<div id="center">
					<%= @content.html.html_safe if @content.html and @content.partial_template.blank? %>
					<%= render_template @content.partial_template if !@content.partial_template.blank? %>
					<%= render_template "elements/social_buttons"%>
			</div>
			<div id="footer">
				<div id="corpright">Anyware Technologies 2007-2011 © All Rights Reserved - Powered by Anysite</div>
			</div>
		</div>
  </div> 
</body> 
</html>

app/views/site/templates/default/_home.html.erb
<div id="homepage_mail" class="left">
<%= @content.html.html_safe if @content.html %>	
</div>

<%= render_template "elements/sidebar"%>

app/views/site/templates/default/_menu.html.erb
<% for @menu_item in getHomepage(@content).children%>
	<% if !@menu_item.menu.blank? %>
	<li><%= link_to @menu_item.menu, site_path(@menu_item.url) %>
		<%= render_template 'sub_menu' %>
	</li>
	<% end -%>
<% end -%>

app/views/site/templates/default/_sub_menu.html.erb
<% if !@menu_item.children.empty? %>
	<ul>
	  <% for @menu_item in @menu_item.children %>
		<% if !@menu_item.menu.blank? %>
		<li><%= link_to @menu_item.menu, site_path(@menu_item.url) %>
			<%= render_template 'sub_menu'-%>
		</li>
		<% end -%>
	  <% end -%>
	</ul>
<% end -%>

app/views/site/templates/default/_top.html.erb
<a href="/"><img src="/images/aw_75.png" width="75" height="75" alt="Logo 75"></a>

app/views/site/templates/default/elements/_sidebar.html.erb
<div id="sidebar" class="right">

<%#= Dir.glob("#{Rails.root.to_s}/app/views/site/templates/default/elements/*.*").first.replace(/.*\//) %><br>
<%#= Dir.new("#{Rails.root.to_s}/app/views/site/templates/default/elements/").entries.last %><br>
<%# Dir.new("#{Rails.root.to_s}/app/views/site/templates/default/elements/").each do |file| %>
<%# unless ['.', '..'].include? file -%>
<%#=     file.gsub(/.html.erb/,"").sub(/_/,"") %>
<%# end -%>
<%# end -%>


</div>

app/views/site/templates/default/elements/_social_buttons.erb
<div class='spread'>
  <div class='twitter_bt'>
    <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="funonrails">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
  </div>
	<div class='gplus_bt'>
		<g:plusone></g:plusone>

		<!-- Place this tag after the last plusone tag -->
		<script type="text/javascript">
		  (function() {
		    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		    po.src = 'https://apis.google.com/js/plusone.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  })();
		</script>
	</div>
  <div class='facebook_bt'>
		<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="" layout="button_count" show_faces="false" width="110" font=""></fb:like>
	</div>
</div>

app/views/templates/default/_top.html.erb
<div id="top">
	<img src="/images/logo_75.png" width="75" height="75" alt="Logo 75">
</div>