config/routes.rb
Anysite::Application.routes.draw do

  namespace :admin do
      resources :templates
      resources :contents do
        resources :comments
      end
      resources :folders
      resources :resources
      match 'index' => 'admin#index'
      match 'contents/tree_node/:id' => 'contents#tree_node'
      match 'folders/tree_node/:id' => 'folders#tree_node'
      match 'resources/update_positions' => 'resources#update_positions'
      match 'contents/order' => 'contents#order'
      match 'contents/order_resources' => 'contents#order_resources'
      match 'folders/order_folders' => 'folders#order_folders'
      match 'folders/order_resources' => 'folders#order_resources'
      match 'contents/import/:id/:type/:object_id' => "contents#import"
  end
  
  
  namespace :site do
    match '*url' => 'contents#by_url'
  end
  
  match 'contact_us' => 'email#contact_us'
      

  devise_for :users

  root :to => "site/contents#index"

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  acts_as_tree
  acts_as_list :scope => "ancestry"
  has_many :resources
  has_one :creator, :foreign_key => "created_by"
  has_one :editor, :foreign_key => "edited_by"
  default_scope :order => "position ASC"
end

app/controllers/admin/folders_controller.rb
class Admin::FoldersController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    @folder = Folder.find(params[:id])
  end
  
  def edit
    @folder = Folder.find(params[:id])
    render "editor"
  end
  
  def new
    @target = Folder.find(params[:target_id])
    @folder = Folder.new
    render "editor"
  end
  
  def update
    @folder = Folder.find(params[:id])
    @folder.update_attributes(params[:folder])
  end
  
  def create
    @parent = Folder.find(params[:target_id])
    @folder = @parent.children.new(params[:folder])
    @folder.save
    render "form"
  end
  
  def destroy
    child = Folder.find(params[:id])
    @folder = child.parent
    child.destroy
  end
  
  def tree_node
    @folder = Folder.find(params[:id])
  end
  
  def order_resources
    params[:folder_resources].each_with_index do |id, position|
      Resource.update(id, :position => position+1)
    end
    render :nothing => true
  end
  
  def order_folders
    params[:folder_folders].each_with_index do |id, position|
      Folder.update(id, :position => position+1)
    end
    render :nothing => true
  end
  
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/admin/folders/_edit.html.erb
<% form_tag admin_folder_path, :method => :put, :remote => true, :id => 'folder_form' do %>
  <%= render :partial => 'form' %>
<% end %>

app/views/admin/folders/_editor.html.erb
<div class="tabs">
    <ul>
        <li id="main_tab" class="tabHeaderActive tab_header">Geral</li>
        <li id="resources_tab" class="tab_header">Resources</li>
        <li id="folders_tab" class="tab_header">Folders</li>
    </ul>
</div>
<div id="tabscontent">
    <div id="main_tab_content" class="tab_content" style="">
	<%if @folder.id then%>
		<%= render :partial => 'edit' %>
	<% else %>
		<%= render :partial => 'new'%>
	<% end %>
    </div>

    <div id="resources_tab_content" class="tab_content" style="display:none;">
        <br /><div><%= render :partial => 'resources' %></div>
    </div>
    <div id="folders_tab_content" class="tab_content" style="display:none;">
        <br /><div><%= render :partial => 'folders' %></div>
    </div>
</div>

app/views/admin/folders/_folders.html.erb
<div>
	<%= link_to 'new folder', new_admin_folder_path(:target_id => @folder.id), :remote => true%>
</div>
<ul id="folder_folders" class="sortable">
	<% if(@folder.id) then @folder.children.each do |folder| %>    
  	<li id="folder_folder_<%= folder.id %>">
			<div class="handle">
				<%= image_tag "admin/tree/open.png"%>&nbsp;
					<%= link_to folder.name, edit_admin_folder_path(folder), :remote => true %>
			</div>
			<%= link_to image_tag("admin/tree/trash.png"), admin_folder_path(folder), :confirm => 'Are you sure?', :method => :delete, :remote => true %>
			<br clear="all"/>
		</li>
	<% end end %>
</ul>
<%= sortable_element('folder_folders', :url => {:controller => 'folders', :action => :order_folders}, :handle => "handle") %>

app/views/admin/folders/_form.html.erb
<!--[form:page]-->
<p><label for="folder_name">Name</label><br/>
<%= text_field 'folder', 'name'  %></p>

<p><label for="folder_description">Description</label><br/>
<%= text_field 'folder', 'description'  %></p>


<%= submit_tag "Salvar", :name => nil %>
<!--[eoform:page]-->

app/views/admin/folders/_new.html.erb
<% form_tag admin_folders_path, :remote => true, :id => 'folder_form' do %>
	<%= text_field_tag 'target_id', @target.id%>
  <%= render :partial => 'form' %>
<% end %>

app/views/admin/folders/_resources.html.erb
<div>
	<%= link_to 'new', new_admin_resource_path(:folder_id => @folder.id), :remote => true%>
</div>
<ul id="folder_resources" class="sortable">
	<% @folder.resources.each do |resource| %>    
  	<li id="folder_resource_<%= resource.id %>">
			<div class="handle">
				<%= image_tag "admin/tree/open.png"%>&nbsp;
					<%= link_to resource.name, edit_admin_resource_path(resource), :remote => true %>
			</div>
			<%= link_to image_tag("admin/tree/trash.png"), admin_resource_path(resource), :confirm => 'Are you sure?', :method => :delete, :remote => true %>
			<br clear="all"/>
		</li>
	<% end %>
</ul>
<%= sortable_element('folder_resources', :url => {:controller => 'folders', :action => :order_resources}, :handle => "handle") %>

app/views/admin/folders/_tree_node.html.erb
<% if !@folder.children.empty? %>
<ul id="resource_folder_<%= @folder.id %>_ul">
<% for subfolder in @folder.children%>
	<%= render :partial => 'tree_node_child', :locals => {:subfolder => subfolder}%>
<% end%>
</ul>
<% end %>

app/views/admin/folders/_tree_node_child.html.erb
<li id="resource_folder_<%= subfolder.id %>">
		<%= link_to image_tag("admin/tree/closed.png"), {:controller => "folders", :action => "tree_node", :id => subfolder.id}, :remote => true, :class => "tree_node_icon" %>
		<%= link_to "#{subfolder.name} (#{subfolder.resources.size})" , edit_admin_folder_path(subfolder), :remote => true, :class => "tree_node" %>
</li>

app/views/admin/folders/destroy.js.erb
$("folders_tab_content").update("<%= escape_javascript(render :partial => 'folders') %>");

app/views/admin/folders/editor.js.erb
$("editor").update("<%= escape_javascript(render :partial => 'editor') %>");

app/views/admin/folders/form.js.erb
$("folder_form").update("<%= escape_javascript(render :partial => 'form') %>");

app/views/admin/folders/tree_node.js.erb
$('resource_folder_<%=@folder.id%>').insert("<%= escape_javascript(render :partial => "tree_node") %>")
tree.openResourceFolder(<%=@folder.id%>);